[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"
default-run = "raytracing"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tempdir = "0.3.7"
