[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"
default-run = "raytracing"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "base1"
path = "src/bin/base1.rs"

[dependencies]
tempdir = "0.3.7"
